namespace Farm.Gameplay
{
    // Action map and action names in Resources/FarmInput.inputactions (generated by Farm.Editor.InputAssetGenerator).
    public static class InputNames
    {
        public const string ResourcePath = "FarmInput";

        public const string GameplayMap = "Gameplay";
        public const string UiMap = "UI";

        public const string Move = "Move";
        public const string UseTool = "UseTool";
        public const string Interact = "Interact";
        public const string Rotate = "Rotate";
        public const string HotbarNext = "HotbarNext";
        public const string HotbarPrev = "HotbarPrev";
        public const string Inventory = "Inventory";
        public const string Pause = "Pause";
        public const string Menu = "Menu";               // the game menu: skills, social, calendar, map, journal, crafting
        public const string Journal = "Journal";         // the game menu opened on the journal
        public const string HotbarPrefix = "Hotbar";     // Hotbar1 .. Hotbar12

        public const string Navigate = "Navigate";
        public const string Submit = "Submit";
        public const string Cancel = "Cancel";
        public const string Point = "Point";
        public const string Click = "Click";
        public const string RightClick = "RightClick";          // a right-click on a window (one item of a stack)
        public const string ScrollWheel = "ScrollWheel";
        public const string TabPrev = "TabPrev";         // previous / next tab in the game menu
        public const string TabNext = "TabNext";

        public const int HotbarSlots = 12;

        // Actions the player may rebind from the options screen (button actions only).
        public static readonly string[] Rebindable =
        {
            UseTool, Interact, Rotate, Inventory, Menu, Journal, HotbarPrev, HotbarNext,
        };
    }
}
