using System.Collections.Generic;
using UnityEngine;

namespace Farm.Data
{
    // Registry of every item and crop definition. One asset at Resources/GameDatabase, generated by the editor
    // content tool and validated by the data validator.
    public sealed class GameDatabase : ScriptableObject
    {
        public const string ResourcePath = "GameDatabase";

        [SerializeField] List<ItemDefinition> _items = new List<ItemDefinition>();
        [SerializeField] List<CropDefinition> _crops = new List<CropDefinition>();

        Dictionary<string, ItemDefinition> _itemLookup;
        Dictionary<string, CropDefinition> _cropLookup;
        readonly List<ItemDefinition> _runtimeItems = new List<ItemDefinition>();
        readonly List<CropDefinition> _runtimeCrops = new List<CropDefinition>();

        public IReadOnlyList<ItemDefinition> Items => _items;
        public IReadOnlyList<CropDefinition> Crops => _crops;

        public static GameDatabase Create(IEnumerable<ItemDefinition> items, IEnumerable<CropDefinition> crops)
        {
            var db = CreateInstance<GameDatabase>();
            db._items.AddRange(items);
            db._crops.AddRange(crops);
            return db;
        }

        public void SetContents(IEnumerable<ItemDefinition> items, IEnumerable<CropDefinition> crops)
        {
            _items = new List<ItemDefinition>(items);
            _crops = new List<CropDefinition>(crops);
            _itemLookup = null;
            _cropLookup = null;
        }

        // Adds a pack's content at runtime (not saved into the asset). Ids must be new: a clash is skipped and
        // reported, because replacing a core item would silently change saved games. Returns the number rejected.
        public int Merge(ContentPack pack)
        {
            EnsureLookups();
            var rejected = 0;
            foreach (var item in pack.Items)
            {
                if (item == null) continue;
                if (_itemLookup.ContainsKey(item.Id))
                {
                    Debug.LogError($"[GameDatabase] Pack '{pack.PackId}' redefines item '{item.Id}'; skipped.");
                    rejected++;
                    continue;
                }
                _itemLookup[item.Id] = item;
                _runtimeItems.Add(item);
            }
            foreach (var crop in pack.Crops)
            {
                if (crop == null) continue;
                if (_cropLookup.ContainsKey(crop.Id))
                {
                    Debug.LogError($"[GameDatabase] Pack '{pack.PackId}' redefines crop '{crop.Id}'; skipped.");
                    rejected++;
                    continue;
                }
                _cropLookup[crop.Id] = crop;
                _runtimeCrops.Add(crop);
            }
            return rejected;
        }

        // Every item including merged pack items (Items lists only the core asset's own content).
        public IEnumerable<ItemDefinition> AllItems
        {
            get
            {
                foreach (var i in _items) if (i != null) yield return i;
                foreach (var i in _runtimeItems) yield return i;
            }
        }

        public IEnumerable<CropDefinition> AllCrops
        {
            get
            {
                foreach (var c in _crops) if (c != null) yield return c;
                foreach (var c in _runtimeCrops) yield return c;
            }
        }

        public bool TryGetItem(string id, out ItemDefinition item)
        {
            EnsureLookups();
            return _itemLookup.TryGetValue(id ?? string.Empty, out item);
        }

        public ItemDefinition GetItem(string id)
        {
            if (TryGetItem(id, out var item)) return item;
            throw new KeyNotFoundException($"Unknown item id '{id}'");
        }

        public bool TryGetCrop(string id, out CropDefinition crop)
        {
            EnsureLookups();
            return _cropLookup.TryGetValue(id ?? string.Empty, out crop);
        }

        public int MaxStack(string itemId) => TryGetItem(itemId, out var item) ? item.MaxStack : 1;

        void EnsureLookups()
        {
            if (_itemLookup != null) return;
            _itemLookup = new Dictionary<string, ItemDefinition>();
            foreach (var item in _items)
                if (item != null) _itemLookup[item.Id] = item;
            _cropLookup = new Dictionary<string, CropDefinition>();
            foreach (var crop in _crops)
                if (crop != null) _cropLookup[crop.Id] = crop;
            foreach (var item in _runtimeItems) _itemLookup[item.Id] = item;
            foreach (var crop in _runtimeCrops) _cropLookup[crop.Id] = crop;
        }

        void OnEnable()
        {
            _itemLookup = null;
            _cropLookup = null;
        }
    }
}
