using System.Collections.Generic;
using UnityEngine;

namespace Farm.Data
{
    // Registry of every item and crop definition. One asset at Resources/GameDatabase, generated by the editor
    // content tool and validated by the data validator.
    public sealed class GameDatabase : ScriptableObject
    {
        public const string ResourcePath = "GameDatabase";

        [SerializeField] List<ItemDefinition> _items = new List<ItemDefinition>();
        [SerializeField] List<CropDefinition> _crops = new List<CropDefinition>();
        [SerializeField] List<WeatherDefinition> _weather = new List<WeatherDefinition>();
        [SerializeField] List<ResourceNodeDefinition> _nodes = new List<ResourceNodeDefinition>();
        [SerializeField] List<UpgradeDefinition> _upgrades = new List<UpgradeDefinition>();
        [SerializeField] List<SpawnTableDefinition> _spawnTables = new List<SpawnTableDefinition>();
        [SerializeField] List<NpcDefinition> _npcs = new List<NpcDefinition>();
        [SerializeField] List<RecipeDefinition> _recipes = new List<RecipeDefinition>();
        [SerializeField] List<PlaceableDefinition> _placeables = new List<PlaceableDefinition>();

        Dictionary<string, ItemDefinition> _itemLookup;
        Dictionary<string, CropDefinition> _cropLookup;
        readonly List<ItemDefinition> _runtimeItems = new List<ItemDefinition>();
        readonly List<CropDefinition> _runtimeCrops = new List<CropDefinition>();
        readonly HashSet<ContentPack> _mergedPacks = new HashSet<ContentPack>();
        readonly List<WeatherDefinition> _runtimeWeather = new List<WeatherDefinition>();
        readonly List<ResourceNodeDefinition> _runtimeNodes = new List<ResourceNodeDefinition>();
        readonly List<UpgradeDefinition> _runtimeUpgrades = new List<UpgradeDefinition>();
        readonly List<SpawnTableDefinition> _runtimeSpawnTables = new List<SpawnTableDefinition>();
        readonly List<NpcDefinition> _runtimeNpcs = new List<NpcDefinition>();
        readonly List<RecipeDefinition> _runtimeRecipes = new List<RecipeDefinition>();
        readonly List<PlaceableDefinition> _runtimePlaceables = new List<PlaceableDefinition>();

        public IReadOnlyList<ItemDefinition> Items => _items;
        public IReadOnlyList<CropDefinition> Crops => _crops;

        public static GameDatabase Create(IEnumerable<ItemDefinition> items, IEnumerable<CropDefinition> crops,
            IEnumerable<WeatherDefinition> weather = null, IEnumerable<ResourceNodeDefinition> nodes = null,
            IEnumerable<UpgradeDefinition> upgrades = null, IEnumerable<SpawnTableDefinition> spawnTables = null)
        {
            var db = CreateInstance<GameDatabase>();
            db._items.AddRange(items);
            db._crops.AddRange(crops);
            if (weather != null) db._weather.AddRange(weather);
            if (nodes != null) db._nodes.AddRange(nodes);
            if (upgrades != null) db._upgrades.AddRange(upgrades);
            if (spawnTables != null) db._spawnTables.AddRange(spawnTables);
            return db;
        }

        public void SetContents(IEnumerable<ItemDefinition> items, IEnumerable<CropDefinition> crops,
            IEnumerable<WeatherDefinition> weather = null, IEnumerable<ResourceNodeDefinition> nodes = null,
            IEnumerable<UpgradeDefinition> upgrades = null, IEnumerable<SpawnTableDefinition> spawnTables = null)
        {
            _spawnTables = spawnTables != null ? new List<SpawnTableDefinition>(spawnTables) : new List<SpawnTableDefinition>();
            _upgrades = upgrades != null ? new List<UpgradeDefinition>(upgrades) : new List<UpgradeDefinition>();
            _nodes = nodes != null ? new List<ResourceNodeDefinition>(nodes) : new List<ResourceNodeDefinition>();
            _items = new List<ItemDefinition>(items);
            _crops = new List<CropDefinition>(crops);
            _weather = weather != null ? new List<WeatherDefinition>(weather) : new List<WeatherDefinition>();
            _itemLookup = null;
            _cropLookup = null;
        }

        // Adds a pack's content at runtime (not saved into the asset). Ids must be new: a clash is skipped and
        // reported, because replacing a core item would silently change saved games. Returns the number rejected.
        public int Merge(ContentPack pack)
        {
            if (!_mergedPacks.Add(pack)) return 0;   // the database asset outlives sessions in the Editor; a pack merges once
            EnsureLookups();
            var rejected = 0;
            foreach (var item in pack.Items)
            {
                if (item == null) continue;
                if (_itemLookup.ContainsKey(item.Id))
                {
                    Debug.LogError($"[GameDatabase] Pack '{pack.PackId}' redefines item '{item.Id}'; skipped.");
                    rejected++;
                    continue;
                }
                _itemLookup[item.Id] = item;
                _runtimeItems.Add(item);
            }
            foreach (var crop in pack.Crops)
            {
                if (crop == null) continue;
                if (_cropLookup.ContainsKey(crop.Id))
                {
                    Debug.LogError($"[GameDatabase] Pack '{pack.PackId}' redefines crop '{crop.Id}'; skipped.");
                    rejected++;
                    continue;
                }
                _cropLookup[crop.Id] = crop;
                _runtimeCrops.Add(crop);
            }
            var known = new HashSet<string>();
            foreach (var w in AllWeather) known.Add(w.Id);
            foreach (var weather in pack.Weather)
            {
                if (weather == null) continue;
                if (!known.Add(weather.Id))
                {
                    Debug.LogError($"[GameDatabase] Pack '{pack.PackId}' redefines weather '{weather.Id}'; skipped.");
                    rejected++;
                    continue;
                }
                _runtimeWeather.Add(weather);
            }
            var knownNodes = new HashSet<string>();
            foreach (var n in AllNodes) knownNodes.Add(n.Id);
            foreach (var node in pack.Nodes)
            {
                if (node == null) continue;
                if (!knownNodes.Add(node.Id))
                {
                    Debug.LogError($"[GameDatabase] Pack '{pack.PackId}' redefines resource node '{node.Id}'; skipped.");
                    rejected++;
                    continue;
                }
                _runtimeNodes.Add(node);
            }
            var knownUpgrades = new HashSet<string>();
            foreach (var u in AllUpgrades) knownUpgrades.Add(u.Id);
            foreach (var upgrade in pack.Upgrades)
            {
                if (upgrade == null) continue;
                if (!knownUpgrades.Add(upgrade.Id))
                {
                    Debug.LogError($"[GameDatabase] Pack '{pack.PackId}' redefines upgrade '{upgrade.Id}'; skipped.");
                    rejected++;
                    continue;
                }
                _runtimeUpgrades.Add(upgrade);
            }
            var knownTables = new HashSet<string>();
            foreach (var t in AllSpawnTables) knownTables.Add(t.Id);
            foreach (var table in pack.SpawnTables)
            {
                if (table == null) continue;
                if (!knownTables.Add(table.Id))
                {
                    Debug.LogError($"[GameDatabase] Pack '{pack.PackId}' redefines spawn table '{table.Id}'; skipped.");
                    rejected++;
                    continue;
                }
                _runtimeSpawnTables.Add(table);
            }
            var knownNpcs = new HashSet<string>();
            foreach (var n in AllNpcs) knownNpcs.Add(n.Id);
            foreach (var npc in pack.Npcs)
            {
                if (npc == null) continue;
                if (!knownNpcs.Add(npc.Id))
                {
                    Debug.LogError($"[GameDatabase] Pack '{pack.PackId}' redefines NPC '{npc.Id}'; skipped.");
                    rejected++;
                    continue;
                }
                _runtimeNpcs.Add(npc);
            }
            var knownRecipes = new HashSet<string>();
            foreach (var r in AllRecipes) knownRecipes.Add(r.Id);
            foreach (var recipe in pack.Recipes)
            {
                if (recipe == null) continue;
                if (!knownRecipes.Add(recipe.Id))
                {
                    Debug.LogError($"[GameDatabase] Pack '{pack.PackId}' redefines recipe '{recipe.Id}'; skipped.");
                    rejected++;
                    continue;
                }
                _runtimeRecipes.Add(recipe);
            }
            var knownPlaceables = new HashSet<string>();
            foreach (var pl in AllPlaceables) knownPlaceables.Add(pl.Id);
            foreach (var placeable in pack.Placeables)
            {
                if (placeable == null) continue;
                if (!knownPlaceables.Add(placeable.Id))
                {
                    Debug.LogError($"[GameDatabase] Pack '{pack.PackId}' redefines placeable '{placeable.Id}'; skipped.");
                    rejected++;
                    continue;
                }
                _runtimePlaceables.Add(placeable);
            }
            return rejected;
        }

        public void SetPlaceables(IEnumerable<PlaceableDefinition> placeables) => _placeables = new List<PlaceableDefinition>(placeables);

        // Every placeable object type, including pack ones.
        public IEnumerable<PlaceableDefinition> AllPlaceables
        {
            get
            {
                foreach (var p in _placeables) if (p != null) yield return p;
                foreach (var p in _runtimePlaceables) if (p != null) yield return p;
            }
        }

        // Replaces the core recipe list (content generation).
        public void SetRecipes(IEnumerable<RecipeDefinition> recipes) => _recipes = new List<RecipeDefinition>(recipes);

        // Every recipe, including pack ones.
        public IEnumerable<RecipeDefinition> AllRecipes
        {
            get
            {
                foreach (var r in _recipes) if (r != null) yield return r;
                foreach (var r in _runtimeRecipes) if (r != null) yield return r;
            }
        }

        // Replaces the core NPC list (content generation).
        public void SetNpcs(IEnumerable<NpcDefinition> npcs) => _npcs = new List<NpcDefinition>(npcs);

        // Every villager, including pack ones.
        public IEnumerable<NpcDefinition> AllNpcs
        {
            get
            {
                foreach (var n in _npcs) if (n != null) yield return n;
                foreach (var n in _runtimeNpcs) if (n != null) yield return n;
            }
        }

        // Every spawn table, including pack ones. Empty means "use ForageDefaults".
        public IEnumerable<SpawnTableDefinition> AllSpawnTables
        {
            get
            {
                foreach (var t in _spawnTables) if (t != null) yield return t;
                foreach (var t in _runtimeSpawnTables) if (t != null) yield return t;
            }
        }

        // Every upgrade definition, including pack ones. Empty means "use UpgradeDefaults".
        public IEnumerable<UpgradeDefinition> AllUpgrades
        {
            get
            {
                foreach (var u in _upgrades) if (u != null) yield return u;
                foreach (var u in _runtimeUpgrades) if (u != null) yield return u;
            }
        }

        // Every resource node definition, including pack ones. Empty means "use NodeDefaults".
        public IEnumerable<ResourceNodeDefinition> AllNodes
        {
            get
            {
                foreach (var n in _nodes) if (n != null) yield return n;
                foreach (var n in _runtimeNodes) if (n != null) yield return n;
            }
        }

        // Every weather definition, including merged pack weather. Empty means "use WeatherDefaults".
        public IEnumerable<WeatherDefinition> AllWeather
        {
            get
            {
                foreach (var w in _weather) if (w != null) yield return w;
                foreach (var w in _runtimeWeather) yield return w;
            }
        }

        // Every item including merged pack items (Items lists only the core asset's own content).
        public IEnumerable<ItemDefinition> AllItems
        {
            get
            {
                foreach (var i in _items) if (i != null) yield return i;
                foreach (var i in _runtimeItems) yield return i;
            }
        }

        public IEnumerable<CropDefinition> AllCrops
        {
            get
            {
                foreach (var c in _crops) if (c != null) yield return c;
                foreach (var c in _runtimeCrops) yield return c;
            }
        }

        public bool TryGetItem(string id, out ItemDefinition item)
        {
            EnsureLookups();
            return _itemLookup.TryGetValue(id ?? string.Empty, out item);
        }

        public ItemDefinition GetItem(string id)
        {
            if (TryGetItem(id, out var item)) return item;
            throw new KeyNotFoundException($"Unknown item id '{id}'");
        }

        public bool TryGetCrop(string id, out CropDefinition crop)
        {
            EnsureLookups();
            return _cropLookup.TryGetValue(id ?? string.Empty, out crop);
        }

        public int MaxStack(string itemId) => TryGetItem(itemId, out var item) ? item.MaxStack : 1;

        void EnsureLookups()
        {
            if (_itemLookup != null) return;
            _itemLookup = new Dictionary<string, ItemDefinition>();
            foreach (var item in _items)
                if (item != null) _itemLookup[item.Id] = item;
            _cropLookup = new Dictionary<string, CropDefinition>();
            foreach (var crop in _crops)
                if (crop != null) _cropLookup[crop.Id] = crop;
            foreach (var item in _runtimeItems) _itemLookup[item.Id] = item;
            foreach (var crop in _runtimeCrops) _cropLookup[crop.Id] = crop;
        }

        void OnEnable()
        {
            _itemLookup = null;
            _cropLookup = null;
        }
    }
}
